import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./pages/navbar/header";
import { Cairo, Amiri, Tajawal } from "next/font/google";
import { ContextProvider } from "@/Context/context";
import "./globals.css"; // لو عندك
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import Footer from "./pages/footer/page";



export const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["300","400","600","700"],
  display: "swap",
  variable: "--font-cairo",
});

export const tajawal = Tajawal({
  subsets: ["arabic"],
  weight: ["200","300","400"],
  display: "swap",
  variable: "--font-tajawal",
})

export const amiri = Amiri({
  subsets: ["arabic"],
  weight: ["400","700"],
  display: "swap",
  variable: "--font-amiri",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cairo.variable} ${tajawal.variable} ${amiri.variable} antialiased`}
      >
        <ContextProvider>
          <Header/>
        {children}
        </ContextProvider>
        <Footer/>
      </body>
    </html>
  );
}
